apiVersion: v1
kind: Service
metadata:
  name: svc-local
  labels:
    zone: prod
    version: v1
    project: test_nginx
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 31111
 